// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.29.3
// source: service_all/v1/data_service.proto

package pkgname_name_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field1 int64 `protobuf:"varint,1,opt,name=Field1,proto3" json:"Field1,omitempty"`
}

func (x *MessageData) Reset() {
	*x = MessageData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_all_v1_data_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageData) ProtoMessage() {}

func (x *MessageData) ProtoReflect() protoreflect.Message {
	mi := &file_service_all_v1_data_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageData.ProtoReflect.Descriptor instead.
func (*MessageData) Descriptor() ([]byte, []int) {
	return file_service_all_v1_data_service_proto_rawDescGZIP(), []int{0}
}

func (x *MessageData) GetField1() int64 {
	if x != nil {
		return x.Field1
	}
	return 0
}

var File_service_all_v1_data_service_proto protoreflect.FileDescriptor

var file_service_all_v1_data_service_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x6c, 0x6c, 0x2f, 0x76, 0x31,
	0x2f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x18, 0x6e, 0x61, 0x6d, 0x65, 0x31, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x32,
	0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x33, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x34, 0x34, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25,
	0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a,
	0x06, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x31, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x44, 0x6f, 0x6b, 0x74, 0x6f, 0x72, 0x47, 0x68, 0x6f, 0x73, 0x74, 0x2f,
	0x74, 0x72, 0x69, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x63, 0x6d, 0x6d, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x6b, 0x67, 0x6e, 0x61, 0x6d, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_all_v1_data_service_proto_rawDescOnce sync.Once
	file_service_all_v1_data_service_proto_rawDescData = file_service_all_v1_data_service_proto_rawDesc
)

func file_service_all_v1_data_service_proto_rawDescGZIP() []byte {
	file_service_all_v1_data_service_proto_rawDescOnce.Do(func() {
		file_service_all_v1_data_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_all_v1_data_service_proto_rawDescData)
	})
	return file_service_all_v1_data_service_proto_rawDescData
}

var file_service_all_v1_data_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_service_all_v1_data_service_proto_goTypes = []interface{}{
	(*MessageData)(nil), // 0: name1.name2.name3.name44.MessageData
}
var file_service_all_v1_data_service_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_all_v1_data_service_proto_init() }
func file_service_all_v1_data_service_proto_init() {
	if File_service_all_v1_data_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_all_v1_data_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_all_v1_data_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_all_v1_data_service_proto_goTypes,
		DependencyIndexes: file_service_all_v1_data_service_proto_depIdxs,
		MessageInfos:      file_service_all_v1_data_service_proto_msgTypes,
	}.Build()
	File_service_all_v1_data_service_proto = out.File
	file_service_all_v1_data_service_proto_rawDesc = nil
	file_service_all_v1_data_service_proto_goTypes = nil
	file_service_all_v1_data_service_proto_depIdxs = nil
}
